# Generated by Django 5.2.17 on 2026-08-19 18:04

import django.db.models.constraints
import django.db.models.deletion
import listening.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, max_length=255, null=True, upload_to=listening.models.exercise_audio_path)),
                ('duration', models.FloatField(blank=True, help_text='Audio length in seconds.', null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(help_text='1-based display order within the exercise.')),
                ('start_time', models.FloatField(help_text='Seconds from the start of the audio.')),
                ('end_time', models.FloatField(help_text='Seconds from the start of the audio.')),
                ('text', models.TextField(help_text='The reference transcript for this segment.')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='listening.listeningexercise')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='listeningexercise',
            index=models.Index(fields=['is_published', '-created_at'], name='ex_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningexercise',
            index=models.Index(fields=['owner', 'status'], name='ex_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='listeningexercise',
            constraint=models.CheckConstraint(condition=models.Q(('duration__isnull', True), ('duration__gt', 0), _connector='OR'), name='exercise_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='listeningexercise',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('status', 'ready'), _connector='OR'), name='exercise_published_requires_ready'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['exercise', 'sequence'], name='seg_ex_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('exercise', 'sequence'), name='uniq_segment_sequence_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__gte', 0)), name='segment_start_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='segment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='segment_sequence_min_1'),
        ),
    ]
