# Generated by Django 5.2.17 on 2026-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningexercise',
            name='transcription_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
