# Generated by Django 5.2.17 on 2026-08-20 19:58

import listening.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0002_listeningexercise_transcription_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningexercise',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Optional question sheet shown alongside the audio during practice.', max_length=255, null=True, upload_to=listening.models.exercise_pdf_path),
        ),
    ]
