# Generated by Django 5.2.17 on 2026-08-20 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listening", "0003_listeningexercise_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="The question number as printed on the sheet."
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="listening.listeningexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "indexes": [models.Index(fields=["exercise", "number"], name="ans_ex_num_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exercise", "number"), name="uniq_answer_number_per_exercise"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("number__gte", 1)), name="answer_number_min_1"
                    ),
                ],
            },
        ),
    ]
