# Generated by Django 5.2.17 on 2026-08-22 05:57

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0004_exerciseanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=1, help_text='1-based display order among siblings.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Null for a root collection. A child may not have children of its own.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listening.exercisecollection')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('parent_id'), nulls_first=True), 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(help_text='1-based order within the collection.')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='listening.listeningexercise')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='listening.exercisecollection')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='exercisecollection',
            index=models.Index(fields=['owner', 'is_published'], name='coll_owner_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisecollection',
            index=models.Index(fields=['parent', 'position'], name='coll_parent_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisecollection',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='collection_position_min_1'),
        ),
        migrations.AddIndex(
            model_name='collectionmembership',
            index=models.Index(fields=['collection', 'position'], name='member_coll_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionmembership',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('collection', 'position'), name='uniq_member_position_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='collectionmembership',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='member_position_min_1'),
        ),
    ]
