# Generated by Django 5.2.17 on 2026-08-27 02:55

import django.db.models.deletion
import writing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Where the workbook came from - book title, publisher, unit.', max_length=255)),
                ('pdf_file', models.FileField(max_length=255, upload_to=writing.models.writing_pdf_path)),
                ('page_count', models.PositiveIntegerField(help_text='Read from the PDF on upload. Never supplied by the client.')),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_page', models.PositiveIntegerField(default=1, help_text='Where the learner left off, for resuming.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when the learner marks the workbook done. Never inferred.', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='writing.writingexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_notebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='writing.writingnotebook')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='writingexercise',
            index=models.Index(fields=['is_published', '-created_at'], name='wex_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='writingexercise',
            index=models.Index(fields=['owner', '-created_at'], name='wex_owner_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='writingexercise',
            constraint=models.CheckConstraint(condition=models.Q(('page_count__gte', 1)), name='writing_exercise_page_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='writingnotebook',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='writing_notebook_unique_user_exercise'),
        ),
        migrations.AddConstraint(
            model_name='writingnotebook',
            constraint=models.CheckConstraint(condition=models.Q(('last_page__gte', 1)), name='writing_notebook_last_page_positive'),
        ),
        migrations.AddConstraint(
            model_name='writingpage',
            constraint=models.UniqueConstraint(fields=('notebook', 'page_number'), name='writing_page_unique_notebook_number'),
        ),
        migrations.AddConstraint(
            model_name='writingpage',
            constraint=models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='writing_page_number_positive'),
        ),
    ]
