# Generated by Django 5.2.17 on 2026-09-23 22:38

import writing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingexercise',
            name='page_count',
            field=models.PositiveIntegerField(help_text='Read from the PDF on upload, or 1 when there is no file. Never supplied by the client.'),
        ),
        migrations.AlterField(
            model_name='writingexercise',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Optional workbook or question sheet shown beside the notebook.', max_length=255, null=True, upload_to=writing.models.writing_pdf_path),
        ),
    ]
