# Generated by Django 5.2.17 on 2026-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, help_text="Google's stable subject identifier, set on first Google sign-in.", max_length=255, null=True, unique=True),
        ),
    ]
