# Generated by Django 5.2.17 on 2026-08-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('submission', 'Submission'), ('reveal', 'Reveal')], default='submission', max_length=20)),
                ('user_answer', models.TextField(blank=True)),
                ('normalized_answer', models.TextField(blank=True)),
                ('expected_snapshot', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, help_text='0-100. Null for reveals.', null=True)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('missing_count', models.PositiveSmallIntegerField(default=0)),
                ('extra_count', models.PositiveSmallIntegerField(default=0)),
                ('incorrect_count', models.PositiveSmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('scoring_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='listening.listeningexercise')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='listening.transcriptsegment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'exercise', '-created_at'], name='att_user_ex_idx'), models.Index(fields=['user', 'segment', '-created_at'], name='att_user_seg_idx'), models.Index(fields=['user', 'kind'], name='att_user_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='attempt_score_range'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'reveal'), _negated=True), ('score__isnull', True), _connector='OR'), name='reveal_has_no_score')],
            },
        ),
    ]
