# Generated by Django 5.2.17 on 2026-09-04 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0005_exercisecollection_collectionmembership_and_more'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='practiceattempt',
            index=models.Index(fields=['kind', '-created_at'], name='att_kind_created_idx'),
        ),
    ]
