# Generated by Django 5.2.17 on 2026-09-15 17:01

import django.db.models.deletion
import reading.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Where the passage came from - book title, publisher, unit.', max_length=255)),
                ('body', models.TextField(help_text='The passage itself. Plain text; paragraphs preserved.')),
                ('word_count', models.PositiveIntegerField(editable=False, help_text='Derived from the body via tokenize(). Never supplied by the client.')),
                ('suggested_wpm', models.PositiveIntegerField(default=250)),
                ('audio_file', models.FileField(blank=True, help_text='Optional follow-up audio. Not synced to paced reading.', max_length=255, null=True, upload_to=reading.models.reading_audio_path)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('paced', 'Paced'), ('highlight', 'Highlight'), ('normal', 'Normal')], default='paced', max_length=20)),
                ('target_wpm', models.PositiveIntegerField()),
                ('strict_mode', models.BooleanField(default=False)),
                ('word_count', models.PositiveIntegerField(help_text='Snapshot of the passage length at start. History stays valid if the body changes.')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('paused_ms', models.PositiveIntegerField(default=0)),
                ('reading_ms', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('actual_wpm', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reading.readingexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='readingexercise',
            index=models.Index(fields=['is_published', '-created_at'], name='rex_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='readingexercise',
            index=models.Index(fields=['owner', '-created_at'], name='rex_owner_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingexercise',
            constraint=models.CheckConstraint(condition=models.Q(('word_count__gte', 1)), name='reading_exercise_word_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='readingexercise',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_wpm__gte', 100), ('suggested_wpm__lte', 500)), name='reading_exercise_suggested_wpm_range'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['user', 'exercise', '-created_at'], name='rsess_user_ex_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.CheckConstraint(condition=models.Q(('target_wpm__gte', 100), ('target_wpm__lte', 500)), name='reading_session_target_wpm_range'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='reading_session_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.CheckConstraint(condition=models.Q(('word_count__gte', 1)), name='reading_session_word_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_wpm__isnull', True), ('finished_at__isnull', True)), models.Q(('actual_wpm__isnull', False), ('finished_at__isnull', False)), _connector='OR'), name='reading_session_wpm_only_when_finished'),
        ),
    ]
